"""initial_models

Revision ID: dbc0a4fcfa98
Revises: 
Create Date: 2026-06-24 14:52:44.051466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc0a4fcfa98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('ml_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_secret', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_user_id', sa.String(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_accounts_seller_id'), 'ml_accounts', ['seller_id'], unique=False)
    op.create_index(op.f('ix_ml_accounts_user_id'), 'ml_accounts', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.String(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('publication_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_import_id'), 'products', ['import_id'], unique=False)
    op.create_index(op.f('ix_products_item_id'), 'products', ['item_id'], unique=False)
    op.create_index(op.f('ix_products_offset'), 'products', ['offset'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_table('publish_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_queue_offset'), 'publish_queue', ['offset'], unique=False)
    op.create_index(op.f('ix_publish_queue_seller_id'), 'publish_queue', ['seller_id'], unique=False)
    op.create_index(op.f('ix_publish_queue_sku'), 'publish_queue', ['sku'], unique=False)
    op.create_table('published_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_items_item_id'), 'published_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_published_items_offset'), 'published_items', ['offset'], unique=True)
    op.create_index(op.f('ix_published_items_seller_id'), 'published_items', ['seller_id'], unique=False)
    op.create_index(op.f('ix_published_items_sku'), 'published_items', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_published_items_sku'), table_name='published_items')
    op.drop_index(op.f('ix_published_items_seller_id'), table_name='published_items')
    op.drop_index(op.f('ix_published_items_offset'), table_name='published_items')
    op.drop_index(op.f('ix_published_items_item_id'), table_name='published_items')
    op.drop_table('published_items')
    op.drop_index(op.f('ix_publish_queue_sku'), table_name='publish_queue')
    op.drop_index(op.f('ix_publish_queue_seller_id'), table_name='publish_queue')
    op.drop_index(op.f('ix_publish_queue_offset'), table_name='publish_queue')
    op.drop_table('publish_queue')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_offset'), table_name='products')
    op.drop_index(op.f('ix_products_item_id'), table_name='products')
    op.drop_index(op.f('ix_products_import_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ml_accounts_user_id'), table_name='ml_accounts')
    op.drop_index(op.f('ix_ml_accounts_seller_id'), table_name='ml_accounts')
    op.drop_table('ml_accounts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
